export const UPDATE_COORDS = "UPDATE_COORDS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";

export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_REQUEST_STATUS = "UPDATE_REQUEST_STATUS";
